# Generated by Django 3.2 on 2023-01-02 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230102_1155'),
        ('users', '0003_alter_user_email'),
    ]

    operations = [
    ]
