# Generated by Django 3.2 on 2022-12-27 12:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 12, 27, 12, 4, 55, 164436), verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='title',
            name='description',
            field=models.TextField(default='default', verbose_name='Краткое описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='title',
            name='rate',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2, verbose_name='Рейтинг'),
        ),
    ]
