# Generated by Django 3.2 on 2022-12-29 07:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0003_alter_title_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Category name')),
                ('slug', models.SlugField(validators=[django.core.validators.RegexValidator(regex='^[-a-zA-Z0-9_]+$')], verbose_name='Category slug')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Genre name')),
                ('slug', models.SlugField(validators=[django.core.validators.RegexValidator(regex='^[-a-zA-Z0-9_]+$')], verbose_name='Genre slug')),
            ],
        ),
        migrations.RemoveField(
            model_name='title',
            name='author',
        ),
        migrations.RemoveField(
            model_name='title',
            name='created_at',
        ),
        migrations.AddField(
            model_name='title',
            name='name',
            field=models.CharField(default='default name', max_length=256, verbose_name='Name of art work'),
        ),
        migrations.AddField(
            model_name='title',
            name='year',
            field=models.IntegerField(default=2001, validators=[django.core.validators.MinValueValidator(-500000), django.core.validators.MaxValueValidator(2022)], verbose_name='Creation year'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='title',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Short description'),
        ),
        migrations.AlterField(
            model_name='title',
            name='rate',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2, verbose_name='Raiting'),
        ),
        migrations.AddField(
            model_name='title',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='titles', to='artworks.category'),
        ),
        migrations.AddField(
            model_name='title',
            name='genre',
            field=models.ManyToManyField(null=True, related_name='titles', to='artworks.Genre'),
        ),
    ]
