# Generated by Django 3.2 on 2023-01-02 11:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0007_auto_20230102_1829'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.RemoveField(
            model_name='title',
            name='category',
        ),
        migrations.RemoveField(
            model_name='title',
            name='year',
        ),
        migrations.AddField(
            model_name='title',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Creation year'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
